# Configuration documentation: https://github.com/openai/codex/blob/main/docs/config.md

# Use unrestricted sandbox (so it has access to `gh`, `jira`, `wrangler`, etc.)
sandbox_mode = "danger-full-access"
model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[shell_environment_policy]
# Clone the entire parent environment into subprocesses
inherit = "all"
# Do not filter out variables containing KEY or TOKEN
ignore_default_excludes = true

[tui]
# Show notifications for turn completion and approval prompts
notifications = true

[features]
web_search_request = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
